import { z } from 'zod';

/**
 * =========================================================
 * INPUT SCHEMA
 * =========================================================
 */

export const generateProposalInputSchema = {
  deal: z
    .object({
      id: z.string().nullable().optional(),
      name: z.string().nullable().optional(),
      description: z.string().nullable().optional(),

      value: z.number().nullable().optional(),
      currency: z.string().nullable().optional(),

      partnerRole: z.string().nullable().optional(),
      product: z.string().nullable().optional(),

      stage: z.string().nullable().optional(),
      status: z.string().nullable().optional(),

      customerId: z.string().nullable().optional(),
      partnerId: z.string().nullable().optional(),
    })
    .describe(
      'AllianceOS deal used to generate the proposal',
    ),

  analysis: z
    .object({
      dealId: z.string().nullable().optional(),
      dealName: z.string().nullable().optional(),

      commercial: z
        .object({
          value: z.number().nullable().optional(),
          currency: z.string().nullable().optional(),
          expectedCloseDate: z
            .string()
            .nullable()
            .optional(),
        })
        .optional(),

      classification: z
        .object({
          product: z.string().nullable().optional(),
          partnerRole: z.string().nullable().optional(),
          stage: z.string().nullable().optional(),
          status: z.string().nullable().optional(),
        })
        .optional(),

      gtmAssessment: z
        .object({
          requiresPartnerIdentification:
            z.boolean().optional(),

          requiresCustomerIdentification:
            z.boolean().optional(),

          proposalReady:
            z.boolean().optional(),

          approvalRequired:
            z.boolean().optional(),

          outreachReady:
            z.boolean().optional(),
        })
        .optional(),

      recommendedNextActions:
        z.array(z.string()).optional(),
    })
    .describe(
      'Output generated by analyze_deal',
    ),

  partner: z
    .object({
      partnerId: z.string(),
      name: z.string(),

      description:
        z.string().nullable().optional(),

      website:
        z.string().nullable().optional(),

      matchScore:
        z.number().optional(),

      matchReasons:
        z.array(z.string()).optional(),
    })
    .nullable()
    .optional()
    .describe(
      'Selected partner from find_partners',
    ),
};

/**
 * =========================================================
 * TYPES
 * =========================================================
 */

type Deal = {
  id?: string | null;
  name?: string | null;
  description?: string | null;

  value?: number | null;
  currency?: string | null;

  partnerRole?: string | null;
  product?: string | null;

  stage?: string | null;
  status?: string | null;

  customerId?: string | null;
  partnerId?: string | null;
};

type Analysis = {
  dealId?: string | null;
  dealName?: string | null;

  commercial?: {
    value?: number | null;
    currency?: string | null;
    expectedCloseDate?: string | null;
  };

  classification?: {
    product?: string | null;
    partnerRole?: string | null;
    stage?: string | null;
    status?: string | null;
  };

  gtmAssessment?: {
    requiresPartnerIdentification?: boolean;
    requiresCustomerIdentification?: boolean;
    proposalReady?: boolean;
    approvalRequired?: boolean;
    outreachReady?: boolean;
  };

  recommendedNextActions?: string[];
};

type Partner = {
  partnerId: string;
  name: string;

  description?: string | null;
  website?: string | null;

  matchScore?: number;
  matchReasons?: string[];
};

/**
 * =========================================================
 * PROPOSAL GENERATOR
 * =========================================================
 */

export async function generateProposal(
  input: {
    deal: Deal;
    analysis: Analysis;
    partner?: Partner | null;
  },
) {
  const deal = input.deal;
  const analysis = input.analysis;
  const partner = input.partner ?? null;

  const value =
    deal.value ??
    analysis.commercial?.value ??
    0;

  const currency =
    deal.currency ??
    analysis.commercial?.currency ??
    'USD';

  const product =
    deal.product ??
    analysis.classification?.product ??
    'AllianceOS Platform';

  const partnerRole =
    deal.partnerRole ??
    analysis.classification?.partnerRole ??
    'Partner';

  const stage =
    deal.stage ??
    analysis.classification?.stage ??
    'DISCOVERY';

  /**
   * -------------------------------------------------------
   * EXECUTIVE SUMMARY
   * -------------------------------------------------------
   */

  const executiveSummary =
    partner
      ? `AllianceOS proposes a ${partnerRole.toLowerCase()} engagement with ${partner.name} around ${product}. The opportunity is currently in ${stage.toLowerCase()} and has an estimated commercial value of ${currency} ${value.toLocaleString()}.`
      : `AllianceOS proposes a ${partnerRole.toLowerCase()} engagement around ${product}. The opportunity is currently in ${stage.toLowerCase()} and has an estimated commercial value of ${currency} ${value.toLocaleString()}.`;

  /**
   * -------------------------------------------------------
   * CUSTOMER PROBLEM
   * -------------------------------------------------------
   */

  const customerProblem =
    deal.description ??
    'The customer requires an enterprise solution aligned with the proposed AllianceOS platform and partner ecosystem.';

  /**
   * -------------------------------------------------------
   * SOLUTION
   * -------------------------------------------------------
   */

  const solution =
    `AllianceOS ${product} will be positioned as the core solution, with the partner contributing the capabilities required to support the ${partnerRole.toLowerCase()} engagement.`;

  /**
   * -------------------------------------------------------
   * PARTNER ROLE
   * -------------------------------------------------------
   */

  const partnerSection =
    partner
      ? {
          partnerId:
            partner.partnerId,

          partnerName:
            partner.name,

          role:
            partnerRole,

          matchScore:
            partner.matchScore ??
            null,

          matchReasons:
            partner.matchReasons ??
            [],
        }
      : null;

  /**
   * -------------------------------------------------------
   * COMMERCIALS
   * -------------------------------------------------------
   */

  const commercials = {
    value,
    currency,
    expectedCloseDate:
      analysis.commercial
        ?.expectedCloseDate ??
      null,
  };

  /**
   * -------------------------------------------------------
   * NEXT STEPS
   * -------------------------------------------------------
   */

  const nextSteps = [
    'Validate customer requirements',
    'Confirm partner participation',
    'Finalize solution scope',
    'Review commercial assumptions',
    'Apply required proposal modifications',
    'Submit proposal for approval',
  ];

  /**
   * -------------------------------------------------------
   * FINAL PROPOSAL
   * -------------------------------------------------------
   */

  return {
    dealId:
      deal.id ??
      analysis.dealId ??
      null,

    status: 'DRAFT',

    proposal: {
      title:
        `${product} - ${partnerRole} Proposal`,

      executiveSummary,

      customerProblem,

      solution,

      partner:
        partnerSection,

      commercials,

      currentStage:
        stage,

      nextSteps,
    },

    generationContext: {
      dealName:
        deal.name ??
        analysis.dealName ??
        null,

      product,

      partnerRole,

      stage,

      analysis,

      generatedAt:
        new Date().toISOString(),
    },

    approval: {
      required: true,
      status: 'PENDING',
    },
  };
}